# Generated by Django 4.1.1 on 2023-06-02 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_musicians_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Musicians",
        ),
    ]
