# Generated by Django 4.1.1 on 2023-06-02 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
